#ifndef BEMBEL_KERNEL_HPP
#define BEMBEL_KERNEL_HPP

#include "./assets/asset-handle.hpp"
#include "./assets/asset-manager.hpp"
#include "./assets/asset.hpp"
#include "./core/application.hpp"
#include "./core/kernel.hpp"
#include "./core/system.hpp"
#include "./display/cursor-icon.hpp"
#include "./display/display-manager.hpp"
#include "./display/display-mode.hpp"
#include "./display/viewport.hpp"
#include "./display/window.hpp"
#include "./events/display-events.hpp"
#include "./events/input-events.hpp"
#include "./input/input-device-button.hpp"
#include "./input/input-device.hpp"
#include "./input/input-manager.hpp"
#include "./input/keyboard.hpp"
#include "./input/mouse.hpp"
#include "./open-gl.hpp"
#include "./rendering/frame-buffer-object.hpp"
#include "./rendering/shader.hpp"
#include "./rendering/texture.hpp"
#include "./scene/entity.hpp"
#include "./scene/position-component.hpp"
#include "./scene/rotation-component.hpp"
#include "./scene/scene.hpp"

#endif // include guards
